# Generated by Django 2.0.6 on 2018-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=200)),
                ('emailsubject', models.TextField()),
                ('emailbody', models.CharField(max_length=200)),
            ],
        ),
    ]
